### ISSUE TITLE
Refresh cache problem?

### ISSUE THREAD

**Issue by MicZet** [kwalski/mysql-redis#1]
Hello @kwalski ! 
I followed your instructions regarding setting async version of MysqlRedis:
``
const { MysqlRedisAsync, HashTypes, Caching } = require("mysql-redis");
``
``
const redis = asyncRedis.createClient(settings.REDIS_PORT, settings.REDIS_HOST);
``
``
const pool = mysql.createPool({
``
``
    host: settings.MYSQL_HOST,
``
``
    user: settings.MYSQL_USER,
``
``
    password: settings.MYSQL_PASS,
``
``
    database: settings.MYSQL_DB
``
``
});
``
``
const promisePool = pool.promise();
``
``
const defaultCacheOptions = {
``
``
    expire: settings.REDIS_CACHE_RETENTION,
``
``
    keyPrefix: "sql.",
``
``
    caching: Caching.CACHE
``
``
};
``
``
const mysqlRedis = new MysqlRedisAsync(
``
``
    promisePool,
``
``
    redis,
``
``
    defaultCacheOptions
``
``
);
``

and then I execute simple query:
``
query = "SELECT * FROM categories where id=2;"
``

with async function
``
        [queryOutput, queryDetails]=await mysqlRedis.query(query,
``
``            { 
``
``            keyPrefix: 'sql.',
``
``                expire: settings.REDIS_CACHE_RETENTION,
``
``                caching: cachingOption
 ``
``           });
``

exchanging cachingOption with either 
Caching.CACHE
or 
Caching.REFRESH

I understand that if CACHE is used it uses Redis, if REFRESH it should update Redis with mysql data and return data from mysql 

So now the problem...

I did query with Caching.CACHE and it created entry in Redis:

``127.0.0.1:6379> keys *``
``1) "sql.M/LnlpXD5l24tMjRGgSX5w=="``

All good

Then I updated DB manually with some small change...

again executing with  Caching.CACHE and it gets (now outdated) data from Redis...
so far - ALL GOOD

so now I execute the same function but with Caching.REFRESH
and what should happen here? 
from what I see it creates another entry in Redis

``
127.0.0.1:6379> keys *
``

``1) "sql.Dg/8759875Xj3gS8cOzUbw=="``
``2) "sql.M/LnlpXD5l24tMjRGgSX5w=="``

and it shows valid (updated) data from DB

but then when I switch back to Caching.CACHE it uses first entry (outdated) from Redis and displays wrong data...

shouldn't it be taken from new Redis entry? 
Did I misunderstand something?

**Comment by kwalski** [comment]
@MicZet If you look at the [hash](https://github.com/kwalski/mysql-redis/blob/63e741e25389f95a248b443607a85286acef2f8a/index.js#L40) function, it is based on your sql statement (including any params you pass in your statement). You must be querying a different statement on two occasions to get a different hash.

**Comment by kwalski** [comment]
closing as it is likely user error
